#!/usr/bin/expect

set timeout 5

expect_before {
    timeout { puts "timeout"; exit 2 }
    eof     { puts "eof";     exit 1 }
}

# Spawn server
spawn build/coap_server -c tests/configs/data_formatting.json
set server_id $spawn_id
expect "Attaching resource string"

# Plain string
spawn coap-client -m put -e "1234WXYZ" coap://127.0.0.1/string
expect -i $server_id "string:PUT: 1234WXYZ\r"

# String containing non-printable characters
spawn coap-client -m put -e "12%01%02%8EF" coap://127.0.0.1/string
expect -i $server_id "string:PUT: 12\\\\x01\\\\x02\\\\x8eF\r"

close -i $server_id

