#!/usr/bin/expect

set timeout 5

# Create data file
spawn sh -c "echo -n \"init value\" > data.bin"
expect eof

# Spawn server
spawn build/coap_server -c tests/configs/protocols/protocol_tcp.json
set server_id $spawn_id
expect "Attaching resource test" {} \
       timeout { puts "timeout"; exit 2 } \
       eof     { puts "eof";     exit 1 }

spawn coap-client -m get coap+tcp://127.0.0.1/test
expect "12345" {} \
       timeout { puts "timeout"; exit 2 } \
       eof     { puts "eof";     exit 1 }
expect eof

close -i $server_id

